apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portfolio
  labels:
    app: dev-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-portfolio
  template:
    metadata:
      labels:
        app: dev-portfolio
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: dev-portfolio
        image: saurabhkr952/dev-portfolio:0ac95e8e98d7fa3809aaae8249ab0bb039aa5142
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"