apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portfolio
  labels:
    app: dev-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-portfolio
  template:
    metadata:
      labels:
        app: dev-portfolio
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: dev-portfolio
        image: saurabhkr952/dev-portfolio:2b8d9c5e4068bfc09271a98c8a620a2522f93fe0
        imagePullPolicy: Always
        ports:
        - containerPort: 80