apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portfolio
  labels:
    app: dev-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-portfolio
  template:
    metadata:
      labels:
        app: dev-portfolio
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: dev-portfolio
        image: saurabhkr952/dev-portfolio:ba31278f7f65f60f91e91bb6f3d8ee9882dbcab6
        imagePullPolicy: Always
        ports:
        - containerPort: 80