apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portfolio
  labels:
    app: dev-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-portfolio
  template:
    metadata:
      labels:
        app: dev-portfolio
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: dev-portfolio
        image: saurabhkr952/dev-portfolio:ae903de31ab84a3a7bfdb08a459b19fcfcc0939a
        imagePullPolicy: Always
        ports:
        - containerPort: 80