apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-portfolio-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev-portfolio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-portfolio
            port:
              number: 31000